#pragma once
#include "Window.h"
#include <Rendering/ShaderProgram.h>
#include <Rendering/Vao.h>
#include <Rendering/Vbo.h>
#include <Gameplay/Camera.h>
#include "Globals.h"
#include <Rendering/Texture.h>
#include <World/Cube.h>
#include "AppContext.h"
#include <World/Chunk.h>
#include <World/World.h>
#include <World/TerrainGeneration.h>
#include <Rendering/Text.h>
#include <Gameplay/DebugUI.h>
#include "Time.h"
#include <Gameplay/Raycaster.h>
#include <Gameplay/CubeSelection.h>
#include <Gameplay/UIRenderer.h>
#include <Gameplay/HUD.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <memory>